name: create-repo
on:
  issues:
    types: [opened]
jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get-keyword
        run: |
          echo level=Undefined >> $GITHUB_OUTPUT
          
          keywords=$(cat keyword-list.txt)
          for keyword in $keywords; do
           echo "level=Undefined" >> $GITHUB_OUTPUT

          keywords=$(cat keyword-list.txt)
          for keyword in $keywords; do
            if [[ "$ISSUE_TITLE" == *"$keyword"* ]]; then
              echo "level=$keyword" >> $GITHUB_OUTPUT
              break
            fi
          done
      - name: get output
        run: |
          echo ${{ steps.get-keyword.outputs.level }}