name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: loop
        run: | 
          count=0
          while true; do
            echo "seconds: $count"
            sleep 1
          done
      - name: echo
        run: echo hello